# NumPy

빠른 연산 속도: NumPy는 내부적으로 C언어로 구현되어 있어 파이썬의 기본 리스트(List)에 비해 월등히 빠른 속도로 대규모 배열 연산을 처리할 수 있다.

강력하고 편리한 기능: 다차원 배열을 생성하고 변형하는 것부터 시작해, 배열 전체에 적용되는 수학 함수, 통계 기능, 선형대수 연산 등 AI 개발에 필요한 거의 모든 종류의 수학적 도구를 제공한다.

데이터 과학 생태계의 중심: Pandas(데이터 분석), Matplotlib(시각화), Scikit-learn(머신러닝), TensorFlow, PyTorch(딥러닝) 등 AI와 데이터 과학에 필수적인 대부분의 라이브러리들이 NumPy를 기반으로 만들어졌거나 NumPy 배열을 기본 데이터 구조로 사용한다.



### ndarray
##### 1. 일차원 배열 만들기

In [ ]:
# 파이썬 리스트
my_list = [1, 2, 3, 4, 5]

# NumPy 배열로 변환
my_array = np.array(my_list)

print(my_array)
# 출력: [1 2 3 4 5]  <- 쉼표(,)가 없는 것을 주목하세요!

print(type(my_list))
# 출력: <class 'list'>

print(type(my_array))
# 출력: <class 'numpy.ndarray'>

- NumPy배열은 모든 원소가 동일한 자료형을 가져야함 -> 빠른 처리 속도


##### 2. 이차원 배열 만들기

In [ ]:
my_list2d = [[1, 2, 3], [4, 5, 6]]
my_matrix = np.array(my_list2d)

print(my_matrix)
# 출력:
# [[1 2 3]
#  [4 5 6]]

##### 3. 배열의 정보 확인

In [ ]:
print(f"배열의 모양(shape): {my_matrix.shape}")   # (2, 6) -> 2행 6열
print(f"배열의 차원(ndim): {my_matrix.ndim}")     # 2 -> 2차원
print(f"데이터 타입(dtype): {my_matrix.dtype}")   # int64 -> 64비트 정수

- `shape` : 배열의 모양 (행, 열)
- `ndim` : 배열의 차원 수
- `dtype` : 배열 원소의 데이터 타입

### 2. 인덱싱, 슬라이싱

##### 인덱싱

In [ ]:
# 위에서 만든 2x3 행렬 my_matrix를 다시 사용
# [[1 2 3]
#  [4 5 6]]

# 1행 2열의 데이터를 가져오기 (0부터 시작하므로 두 번째 행, 세 번째 열)
element = my_matrix[1, 2]
print(f"1행 2열의 원소: {element}")  # 출력: 6

# 0행 전체를 가져오기
row0 = my_matrix[0, :]  # : 는 '전체'를 의미
print(f"0행 전체: {row0}") # 출력: [1 2 3]

# 1열 전체를 가져오기
col1 = my_matrix[:, 1]
print(f"1열 전체: {col1}") # 출력: [2 5]

##### 불리언 인덱싱

In [ ]:
data = np.array([10, 25, 30, 15, 40])

# data에서 20보다 큰 값만 찾아내기
# 1. 조건을 검사하면 True/False로 구성된 배열이 나옵니다.
condition = data > 20
print(f"조건 검사 결과: {condition}")
# 출력: [False  True  True False  True]

# 2. 이 조건 배열을 인덱스 자리에 넣으면 True인 위치의 값만 추출됩니다.
result = data[condition]
print(f"20보다 큰 값들: {result}")
# 출력: [25 30 40]

# 한 줄로도 가능합니다.
print(f"한 줄로 처리: {data[data > 20]}")

-> 조건이 참(True)인 데이터만 골라내는 연산

### 3. 배열 연산

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# 배열의 모든 요소에 10 더하기
print(f"더하기: {arr + 10}")
# 출력: [11 12 13 14 15]

# 배열의 모든 요소에 2 곱하기
print(f"곱하기: {arr * 2}")
# 출력: [ 2  4  6  8 10]

# 배열 간의 연산도 가능합니다. (모양(shape)이 같아야 함)
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
print(f"배열 간 덧셈: {arr1 + arr2}")
# 출력: [11 22 33]

##### 브로드캐스팅 (Broadcasting)

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 행렬
vector = np.array([10, 20, 30])           # 1x3 벡터

# 2x3 행렬의 각 행에 1x3 벡터를 더하기
# NumPy는 vector를 아래와 같이 확장하여 연산합니다.
# [[10, 20, 30],
#  [10, 20, 30]]
result = matrix + vector
print(result)
# 출력:
# [[11 22 33]
#  [14 25 36]]

Numpy가 부족한 부분을 알아서 확장해서 채워줌