# TensorFlow에 대하여

#### <span style='background-color:#fff5b1'><span style='color:indigo'>기본 Tensor 모듈</span>

##### Tensor를 생성해보아요

In [ ]:
tf.constant()

tf.Variable()

### 예시 코드
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
v = tf.Variable(tf.ones((2, 2)))

### 출력 예시
x: [[1. 2.]
    [3. 4.]]
v: [[1. 1.]
    [1. 1.]]

##### 다른 자료형을 텐서로 변환

In [ ]:
tf.convert_to_tensor()

##### 모양 변환

In [ ]:
tf.reshape()

tf.transpose()

### 예시 코드
y = tf.reshape(x, (4,))
z = tf.cast(x, tf.int32)

### 출력 예시
y: [1. 2. 3. 4.]
z: [1 2 3 4]

##### 자료형 변환

In [ ]:
tf.cast()

##### 텐서 결합 및 분리

In [ ]:
tf.concat()

tf.stack()

tf.split()


### 예시 코드
a = tf.stack([y, y])
b = tf.concat([a, a], axis=0)
c1, c2 = tf.split(y, num_or_size_splits=2)

### 출력 예시
a:
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]

b:
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]

c1: [1. 2.]
c2: [3. 4.]

#### <span style='background-color:#fff5b1'><span style='color:indigo'>수학, 통계를 위한 연산 모듈</span>

##### 연산 모듈

In [ ]:
t = tf.constant([[1., 2.], [3., 4.]])
u = tf.constant([[5., 6.], [7., 8.]])

s = tf.math.add(t, u)          
# 덧셈

m = tf.reduce_mean(t, axis=0)  
# 열 평균

mx = tf.reduce_max(t)          
# 최댓값

e = tf.math.exp(t)              
# e^x

l = tf.math.log(t)              
# ln(x)

matmul = tf.linalg.matmul(t, u) 
# 행렬곱

det = tf.linalg.det(t)          
# 행렬식

##### 출력 예시

In [ ]:
s: [[ 6.  8.]
    [10. 12.]]
m: [2. 3.]
mx: 4.0
e: [[ 2.7182817  7.389056 ]
    [20.085537  54.59815  ]]
l: [[0.        0.6931472]
    [1.0986123 1.3862944]]
matmul: [[19. 22.]
         [43. 50.]]
det: -2.0

#### <span style='background-color:#fff5b1'><span style='color:indigo'>데이터 처리 및 입출력</span>

#### 모듈 설명

In [ ]:
# tf.data
def preprocess(x):
    return x * 2

ds = tf.data.Dataset.from_tensor_slices(tf.range(10))
ds = ds.shuffle(10).map(preprocess).batch(4)

print("첫 배치 예시:")
for batch in ds.take(1):
    print(batch.numpy())

# tf.io (직렬화/역직렬화)
s = tf.constant("hello")
encoded = tf.io.serialize_tensor(s)
decoded = tf.io.parse_tensor(encoded, out_type=tf.string)
print("decoded:", decoded.numpy().decode())

# tf.image (임의 이미지 변환)
img = tf.random.uniform((128, 128, 3))
resized = tf.image.resize(img, (64, 64))
flipped = tf.image.flip_left_right(resized)
print("resized shape:", resized.shape)
print("flipped shape:", flipped.shape)


#### 예시 코드 답

In [ ]:
첫 배치 예시:
[ 4 14  8  6]
decoded: hello
resized shape: (64, 64, 3)
flipped shape: (64, 64, 3)


#### <span style='background-color:#fff5b1'><span style='color:indigo'>데이터 처리 및 입출력</span>

##### 모듈 설명

In [ ]:
# 더미 데이터 생성
X = tf.random.normal((200, 20))
y = tf.cast(tf.reduce_sum(X, axis=1) > 0, tf.int32)

# 모델 정의
inp = tf.keras.Input(shape=(20,))
h1 = tf.keras.layers.Dense(32, activation='relu')(inp)
out = tf.keras.layers.Dense(1, activation='sigmoid')(h1)
model = tf.keras.Model(inp, out)

model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
model.fit(X, y, epochs=3, batch_size=32, verbose=0)

# 저장 후 로드
model.save("demo_model.keras")
loaded = tf.keras.models.load_model("demo_model.keras")
print("Eval:", loaded.evaluate(X, y, verbose=0))


##### 예시 답안

In [ ]:
Eval: [0.6741139888763428, 0.60999995470047]

#### <span style='background-color:#fff5b1'><span style='color:indigo'>Numpy와 Tensorflow의 관계</span>

##### numpy와 tensorflow는 호환되며, 상호 변환이 자동으로 일어날 수 있다.

In [ ]:
import numpy as np
import tensorflow as tf

# NumPy → TensorFlow
np_arr = np.array([1, 2, 3])
tf_tensor = tf.constant(np_arr)

# TensorFlow → NumPy
np_back = tf_tensor.numpy()
print("NumPy to TensorFlow:", tf_tensor)
print("TensorFlow to NumPy:", np_back)


####출력 예시
# NumPy to TensorFlow: tf.Tensor([1 2 3], shape=(3,), dtype=int64)
# TensorFlow to NumPy: [1 2 3]


##### Q. 왜 tensorflow를 출력할 때, 주로 '.numpy'를 사용할까?

In [ ]:
#출력 형식에 차이가 있기 때문이다.

#Numpy : 값만 표시 
#([1 2 3])	

#TensorFlow : 값 + shape + dtype 표시 
#(tf.Tensor([1 2 3], shape=(3,), dtype=int64))

##### 한 줄 정리

In [ ]:
#데이터 만들기/간단 계산은 np, 가속·미분 필요한 계산은 tf